import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import RevealController from './components/RevealController';
import ParallaxController from './components/ParallaxController';
import CursorGlow from './components/CursorGlow';
import Magnetic from './components/Magnetic';
import RegisterFade from './components/RegisterFade';

// ─────────────────────────────────────────────────────────────────────────────
// Fonts — self-hosted, latin subset, variable. Only Bodoni Moda and Hanken
// Grotesk are preloaded; JetBrains Mono loads on demand.
// size-adjust against the fallback is generated by next/font (adjustFontFallback).
// ─────────────────────────────────────────────────────────────────────────────
const display = localFont({
  src: '../fonts/BodoniModa-latin-wght.woff2',
  weight: '400 900',
  variable: '--font-display',
  display: 'swap',
  preload: true,
  adjustFontFallback: 'Times New Roman',
});

const body = localFont({
  src: '../fonts/HankenGrotesk-latin-wght.woff2',
  weight: '100 900',
  variable: '--font-body',
  display: 'swap',
  preload: true,
  adjustFontFallback: 'Arial',
});

const mono = localFont({
  src: '../fonts/JetBrainsMono-latin-wght.woff2',
  weight: '100 800',
  variable: '--font-mono',
  display: 'swap',
  preload: false,
  adjustFontFallback: false,
  fallback: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
});

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
};

// ─────────────────────────────────────────────────────────────────────────────
// Metadata
// ─────────────────────────────────────────────────────────────────────────────
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000';
const TITLE = 'Muhammad Qasim | Full-stack & Mobile Engineer';
const DESCRIPTION =
  'Full-stack and mobile engineer building web apps and Flutter mobile apps, and shipping them to production.';

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  authors: [{ name: 'Muhammad Qasim' }],
  alternates: { canonical: '/' },
  icons: { icon: '/favicon.svg' },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: '/',
    siteName: 'Muhammad Qasim',
    type: 'website',
  },
  twitter: {
    card: 'summary',
    title: TITLE,
    description: DESCRIPTION,
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Root Layout
// ─────────────────────────────────────────────────────────────────────────────

// Marks JS as available, so progressive enhancements (the scroll-driven hero) key on it.
const JS_FLAG = "document.documentElement.classList.add('js')";

// Runs before first paint: applies a saved theme choice so there is no flash of the wrong
// theme. With no saved choice the CSS follows the system preference. try/catch because
// storage can be blocked.
const THEME_INIT =
  "try{var t=localStorage.getItem('theme');if(t==='light'||t==='dark')document.documentElement.setAttribute('data-theme',t)}catch(e){}";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${display.variable} ${body.variable} ${mono.variable}`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT + ';' + JS_FLAG }} />
      </head>
      <body>
        <a href="#main" className="skip-link">
          Skip to content
        </a>
        <CursorGlow />
        {children}
        <RevealController />
        <ParallaxController />
        <Magnetic />
        <RegisterFade />
      </body>
    </html>
  );
}
