import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import RevealController from './components/RevealController';

// ─────────────────────────────────────────────────────────────────────────────
// Fonts — self-hosted, latin subset, variable. Only Bodoni Moda and Hanken
// Grotesk are preloaded; JetBrains Mono loads on demand.
// size-adjust against the fallback is generated by next/font (adjustFontFallback).
// ─────────────────────────────────────────────────────────────────────────────
const display = localFont({
  src: '../fonts/BodoniModa-latin-wght.woff2',
  weight: '400 900',
  variable: '--font-display',
  display: 'swap',
  preload: true,
  adjustFontFallback: 'Times New Roman',
});

const body = localFont({
  src: '../fonts/HankenGrotesk-latin-wght.woff2',
  weight: '100 900',
  variable: '--font-body',
  display: 'swap',
  preload: true,
  adjustFontFallback: 'Arial',
});

const mono = localFont({
  src: '../fonts/JetBrainsMono-latin-wght.woff2',
  weight: '100 800',
  variable: '--font-mono',
  display: 'swap',
  preload: false,
  adjustFontFallback: false,
  fallback: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
});

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
};

// ─────────────────────────────────────────────────────────────────────────────
// Metadata
// ─────────────────────────────────────────────────────────────────────────────
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000';
const TITLE = 'Muhammad Qasim | Full-stack & Mobile Engineer';
const DESCRIPTION =
  'Full-stack and mobile engineer building web apps and Flutter mobile apps, and shipping them to production.';

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  authors: [{ name: 'Muhammad Qasim' }],
  alternates: { canonical: '/' },
  icons: { icon: '/favicon.svg' },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: '/',
    siteName: 'Muhammad Qasim',
    type: 'website',
  },
  twitter: {
    card: 'summary',
    title: TITLE,
    description: DESCRIPTION,
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Root Layout
// ─────────────────────────────────────────────────────────────────────────────
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${display.variable} ${body.variable} ${mono.variable}`}>
      <body>
        <a href="#main" className="skip-link">
          Skip to content
        </a>
        {children}
        <RevealController />
      </body>
    </html>
  );
}
